"""role_permission

Revision ID: 090d55b2cb86
Revises: 599491d733dd
Create Date: 2020-06-30 15:11:51.465586

"""
from alembic import op
from datetime import datetime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12'
down_revision = 'e18fa72cc352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET FOREIGN_KEY_CHECKS = 0;')
    op.execute('TRUNCATE TABLE roles;')
    op.execute(
        "INSERT INTO roles (code, name, has_all_permissions, is_active, created_at, updated_at) VALUES ('super_admin', 'Quản lý cấp cao', 1, 1, '2020-06-30 16:51:59', '2020-06-30 16:51:59')"
    )
    op.execute('TRUNCATE TABLE permissions;')
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('user:read:ui', 'Xem người dùng FE', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('user:read', 'Xem người dùng', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('user:create', 'Tạo mới người dùng', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('user:update', 'Cập nhật người dùng', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('user:delete', 'Xóa người dùng', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")

    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('role:read:ui', 'Xem quyền FE', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('role:read', 'Xem quyền', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('role:create', 'Tạo mới quyền', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('role:update', 'Cập nhật quyền', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('role:delete', 'Xóa quyền', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")

    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('permission:read:ui', 'Xem permission FE', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('permission:read', 'Xem permission', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('permission:create', 'Tạo mới permission', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('permission:update', 'Cập nhật permission', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")
    op.execute("INSERT INTO permissions (code, name, created_at, updated_at, is_active) VALUES ('permission:delete', 'Xóa permission', '2020-06-30 16:51:59', '2020-06-30 16:51:59', 1)")

    op.execute('SET FOREIGN_KEY_CHECKS = 1;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET FOREIGN_KEY_CHECKS = 0;')
    op.execute(
        "DELETE FROM role_permissions WHERE 1=1"
    )
    op.execute(
        "DELETE FROM roles WHERE 1=1"
    )
    op.execute(
        "DELETE FROM permissions WHERE 1=1"
    )
    op.execute('SET FOREIGN_KEY_CHECKS = 1;')
    # ### end Alembic commands ###