"""rename_field_username

Revision ID: 599491d733dd
Revises: 2b5427b10969
Create Date: 2020-06-30 09:31:36.282449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '599491d733dd'
down_revision = '2b5427b10969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
